
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jun 26 13:53:50 CEST 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 28;
  public static final int READ = 19;
  public static final int LSQUAREBRACE = 16;
  public static final int IDENT = 2;
  public static final int PLUS = 24;
  public static final int RPAREN = 11;
  public static final int CHAR = 4;
  public static final int SEMI = 13;
  public static final int DECREMENT = 22;
  public static final int RETURN = 18;
  public static final int LPAREN = 10;
  public static final int RCURLYBRACE = 8;
  public static final int PROGRAM = 6;
  public static final int NUM = 3;
  public static final int COMMA = 14;
  public static final int RSQUAREBRACE = 17;
  public static final int EOF = 0;
  public static final int DIV = 27;
  public static final int INCREMENT = 21;
  public static final int MINUS = 25;
  public static final int PRINT = 20;
  public static final int CONST = 12;
  public static final int error = 1;
  public static final int NEW = 23;
  public static final int LCURLYBRACE = 7;
  public static final int BOOL = 5;
  public static final int ASSIGNMENT = 15;
  public static final int MUL = 26;
  public static final int VOID = 9;
}

